// Code generated by protoc-gen-go.
// source: client.proto
// DO NOT EDIT!

/*
Package pb_client is a generated protocol buffer package.

It is generated from these files:
	client.proto

It has these top-level messages:
	UserInfo
	LoginReq
	LoginResp
	SendMessageReq
	SendMessageResp
	MessageNotify
*/
package pb_client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type UserInfo struct {
	Userid   uint32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginReq struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginResp struct {
	UserInfo *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
}

func (m *LoginResp) Reset()                    { *m = LoginResp{} }
func (m *LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()               {}
func (*LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type SendMessageReq struct {
	Receiver uint32 `protobuf:"varint,1,opt,name=receiver" json:"receiver,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *SendMessageReq) Reset()                    { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string            { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()               {}
func (*SendMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SendMessageResp struct {
}

func (m *SendMessageResp) Reset()                    { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string            { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()               {}
func (*SendMessageResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type MessageNotify struct {
	Sender  uint32 `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *MessageNotify) Reset()                    { *m = MessageNotify{} }
func (m *MessageNotify) String() string            { return proto.CompactTextString(m) }
func (*MessageNotify) ProtoMessage()               {}
func (*MessageNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*UserInfo)(nil), "pb_client.UserInfo")
	proto.RegisterType((*LoginReq)(nil), "pb_client.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "pb_client.LoginResp")
	proto.RegisterType((*SendMessageReq)(nil), "pb_client.SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "pb_client.SendMessageResp")
	proto.RegisterType((*MessageNotify)(nil), "pb_client.MessageNotify")
}

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x59, 0xc1, 0x35, 0x19, 0x5d, 0xc5, 0x28, 0x52, 0x3c, 0x2d, 0x39, 0x79, 0x2a, 0xa2,
	0x67, 0x05, 0x2f, 0x82, 0xa0, 0x1e, 0x22, 0x9e, 0x97, 0xdd, 0xec, 0x6c, 0x09, 0xd5, 0x49, 0x4c,
	0x52, 0xc1, 0x7f, 0x6f, 0xda, 0xa6, 0x01, 0x0f, 0xde, 0xe6, 0x6b, 0x5f, 0xde, 0x7c, 0x0c, 0x1c,
	0xe9, 0x0f, 0x83, 0x14, 0x6b, 0xe7, 0x6d, 0xb4, 0x82, 0xbb, 0xcd, 0x6a, 0xfc, 0x20, 0xef, 0x81,
	0xbd, 0x07, 0xf4, 0x4f, 0xb4, 0xb3, 0xe2, 0x02, 0xe6, 0x5d, 0x9a, 0xcd, 0xb6, 0x9a, 0x2d, 0x67,
	0x57, 0x0b, 0x95, 0x49, 0x5c, 0x02, 0x23, 0xa3, 0x5b, 0x5a, 0x7f, 0x62, 0xb5, 0x97, 0xfe, 0x70,
	0x55, 0x58, 0x2e, 0x81, 0x3d, 0xdb, 0xc6, 0x90, 0xc2, 0x2f, 0x71, 0x0e, 0xfb, 0xd1, 0xb6, 0x48,
	0xc3, 0x73, 0xae, 0x46, 0x90, 0x77, 0xc0, 0x73, 0x22, 0x38, 0x71, 0x0d, 0xbc, 0x2f, 0x5d, 0x99,
	0xb4, 0x6f, 0x88, 0x1d, 0xde, 0x9c, 0xd5, 0xc5, 0xa6, 0x9e, 0x54, 0x14, 0xeb, 0xf2, 0x24, 0x1f,
	0xe1, 0xf8, 0x0d, 0x69, 0xfb, 0x82, 0x21, 0xac, 0x1b, 0xec, 0xd7, 0x24, 0x1d, 0x8f, 0x1a, 0xcd,
	0x37, 0xfa, 0x2c, 0x5a, 0x58, 0x54, 0x70, 0xa0, 0x2d, 0xc5, 0xd4, 0x95, 0x4d, 0x27, 0x94, 0xa7,
	0x70, 0xf2, 0xa7, 0x27, 0x38, 0xf9, 0x00, 0x8b, 0x8c, 0xaf, 0x36, 0x9a, 0xdd, 0x4f, 0x7f, 0x80,
	0x90, 0x32, 0xa5, 0x37, 0xd3, 0xff, 0xad, 0x9b, 0xf9, 0x70, 0xd0, 0xdb, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0xeb, 0x78, 0x7a, 0x60, 0x01, 0x00, 0x00,
}
