// Code generated by protoc-gen-go.
// source: table.proto
// DO NOT EDIT!

/*
Package table is a generated protocol buffer package.

It is generated from these files:
	table.proto

It has these top-level messages:
	TableInfo
	TimerInfo
	EnterRoomReq
	EnterRoomResp
	ExitRoomReq
	ExitRoomResp
	UpdateTableInfoReq
	UpdateTableInfoResp
	QueryTableInfoReq
	QueryTableInfoResp
	QueryByUseridReq
	QueryByUseridResp
*/
package table

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type TableInfo struct {
	Id         int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Roomid     int32    `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	Version    int32    `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	IsSetTimer bool     `protobuf:"varint,4,opt,name=is_set_timer,json=isSetTimer" json:"is_set_timer,omitempty"`
	GameInfo   []byte   `protobuf:"bytes,5,opt,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`
	Userids    []uint32 `protobuf:"varint,6,rep,packed,name=userids" json:"userids,omitempty"`
}

func (m *TableInfo) Reset()                    { *m = TableInfo{} }
func (m *TableInfo) String() string            { return proto.CompactTextString(m) }
func (*TableInfo) ProtoMessage()               {}
func (*TableInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TimerInfo struct {
	Duration int32 `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
}

func (m *TimerInfo) Reset()                    { *m = TimerInfo{} }
func (m *TimerInfo) String() string            { return proto.CompactTextString(m) }
func (*TimerInfo) ProtoMessage()               {}
func (*TimerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EnterRoomReq struct {
	Roomid int32  `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Userid uint32 `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
}

func (m *EnterRoomReq) Reset()                    { *m = EnterRoomReq{} }
func (m *EnterRoomReq) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomReq) ProtoMessage()               {}
func (*EnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EnterRoomResp struct {
	Result    int32      `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Roomid    int32      `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	Tableid   int64      `protobuf:"varint,3,opt,name=tableid" json:"tableid,omitempty"`
	TableInfo *TableInfo `protobuf:"bytes,4,opt,name=table_info,json=tableInfo" json:"table_info,omitempty"`
}

func (m *EnterRoomResp) Reset()                    { *m = EnterRoomResp{} }
func (m *EnterRoomResp) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomResp) ProtoMessage()               {}
func (*EnterRoomResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnterRoomResp) GetTableInfo() *TableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

type ExitRoomReq struct {
	Userid uint32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *ExitRoomReq) Reset()                    { *m = ExitRoomReq{} }
func (m *ExitRoomReq) String() string            { return proto.CompactTextString(m) }
func (*ExitRoomReq) ProtoMessage()               {}
func (*ExitRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ExitRoomResp struct {
	Result  int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Tableid int64 `protobuf:"varint,2,opt,name=tableid" json:"tableid,omitempty"`
}

func (m *ExitRoomResp) Reset()                    { *m = ExitRoomResp{} }
func (m *ExitRoomResp) String() string            { return proto.CompactTextString(m) }
func (*ExitRoomResp) ProtoMessage()               {}
func (*ExitRoomResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UpdateTableInfoReq struct {
	Id        int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Version   int32      `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	GameInfo  []byte     `protobuf:"bytes,3,opt,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`
	GameOver  bool       `protobuf:"varint,4,opt,name=game_over,json=gameOver" json:"game_over,omitempty"`
	TimerInfo *TimerInfo `protobuf:"bytes,5,opt,name=timer_info,json=timerInfo" json:"timer_info,omitempty"`
}

func (m *UpdateTableInfoReq) Reset()                    { *m = UpdateTableInfoReq{} }
func (m *UpdateTableInfoReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateTableInfoReq) ProtoMessage()               {}
func (*UpdateTableInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateTableInfoReq) GetTimerInfo() *TimerInfo {
	if m != nil {
		return m.TimerInfo
	}
	return nil
}

type UpdateTableInfoResp struct {
	Result    int32      `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	TableInfo *TableInfo `protobuf:"bytes,2,opt,name=table_info,json=tableInfo" json:"table_info,omitempty"`
}

func (m *UpdateTableInfoResp) Reset()                    { *m = UpdateTableInfoResp{} }
func (m *UpdateTableInfoResp) String() string            { return proto.CompactTextString(m) }
func (*UpdateTableInfoResp) ProtoMessage()               {}
func (*UpdateTableInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateTableInfoResp) GetTableInfo() *TableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

type QueryTableInfoReq struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *QueryTableInfoReq) Reset()                    { *m = QueryTableInfoReq{} }
func (m *QueryTableInfoReq) String() string            { return proto.CompactTextString(m) }
func (*QueryTableInfoReq) ProtoMessage()               {}
func (*QueryTableInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type QueryTableInfoResp struct {
	Result    int32      `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	TableInfo *TableInfo `protobuf:"bytes,2,opt,name=table_info,json=tableInfo" json:"table_info,omitempty"`
}

func (m *QueryTableInfoResp) Reset()                    { *m = QueryTableInfoResp{} }
func (m *QueryTableInfoResp) String() string            { return proto.CompactTextString(m) }
func (*QueryTableInfoResp) ProtoMessage()               {}
func (*QueryTableInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryTableInfoResp) GetTableInfo() *TableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

type QueryByUseridReq struct {
	Userid uint32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *QueryByUseridReq) Reset()                    { *m = QueryByUseridReq{} }
func (m *QueryByUseridReq) String() string            { return proto.CompactTextString(m) }
func (*QueryByUseridReq) ProtoMessage()               {}
func (*QueryByUseridReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type QueryByUseridResp struct {
	Roomid  int32 `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Tableid int64 `protobuf:"varint,2,opt,name=tableid" json:"tableid,omitempty"`
}

func (m *QueryByUseridResp) Reset()                    { *m = QueryByUseridResp{} }
func (m *QueryByUseridResp) String() string            { return proto.CompactTextString(m) }
func (*QueryByUseridResp) ProtoMessage()               {}
func (*QueryByUseridResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*TableInfo)(nil), "table.TableInfo")
	proto.RegisterType((*TimerInfo)(nil), "table.TimerInfo")
	proto.RegisterType((*EnterRoomReq)(nil), "table.EnterRoomReq")
	proto.RegisterType((*EnterRoomResp)(nil), "table.EnterRoomResp")
	proto.RegisterType((*ExitRoomReq)(nil), "table.ExitRoomReq")
	proto.RegisterType((*ExitRoomResp)(nil), "table.ExitRoomResp")
	proto.RegisterType((*UpdateTableInfoReq)(nil), "table.UpdateTableInfoReq")
	proto.RegisterType((*UpdateTableInfoResp)(nil), "table.UpdateTableInfoResp")
	proto.RegisterType((*QueryTableInfoReq)(nil), "table.QueryTableInfoReq")
	proto.RegisterType((*QueryTableInfoResp)(nil), "table.QueryTableInfoResp")
	proto.RegisterType((*QueryByUseridReq)(nil), "table.QueryByUseridReq")
	proto.RegisterType((*QueryByUseridResp)(nil), "table.QueryByUseridResp")
}

var fileDescriptor0 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0xc7, 0x99, 0xe4, 0xf6, 0xeb, 0xb4, 0xbd, 0xf4, 0xce, 0x05, 0x09, 0xea, 0xa2, 0x8c, 0x88,
	0xc5, 0x45, 0x05, 0xdd, 0x8b, 0x14, 0xba, 0x70, 0x25, 0x8e, 0xed, 0x52, 0x4b, 0x4a, 0x46, 0x19,
	0x68, 0x9b, 0x3a, 0x33, 0x29, 0xf6, 0x15, 0x7c, 0x13, 0x7d, 0x4a, 0x27, 0xa7, 0x49, 0x9a, 0x54,
	0x8d, 0x1b, 0x77, 0xe7, 0x63, 0x38, 0xf9, 0x9d, 0xff, 0xff, 0x10, 0x68, 0x1a, 0x7f, 0x3a, 0x13,
	0xfd, 0xa5, 0x0a, 0x4d, 0x48, 0x2b, 0x98, 0xb0, 0x77, 0x02, 0x8d, 0x51, 0x1c, 0x5d, 0x2f, 0x1e,
	0x43, 0xfa, 0x17, 0x1c, 0x19, 0x78, 0xa4, 0x4b, 0x7a, 0x2e, 0xb7, 0x11, 0xdd, 0x83, 0xaa, 0x0a,
	0xc3, 0xb9, 0xad, 0x39, 0xb6, 0x56, 0xe1, 0x49, 0x46, 0x3d, 0xa8, 0xad, 0x84, 0xd2, 0x32, 0x5c,
	0x78, 0x2e, 0x36, 0xd2, 0x94, 0x76, 0xa1, 0x25, 0xf5, 0x44, 0x0b, 0x33, 0x31, 0x72, 0x2e, 0x94,
	0xf7, 0xc7, 0xb6, 0xeb, 0x1c, 0xa4, 0xbe, 0x13, 0x66, 0x14, 0x57, 0xe8, 0x01, 0x34, 0x9e, 0xfc,
	0xb9, 0x98, 0x48, 0xfb, 0x41, 0xaf, 0x62, 0xdb, 0x2d, 0x5e, 0x8f, 0x0b, 0x08, 0x70, 0x08, 0xb5,
	0x48, 0x0b, 0x25, 0x03, 0xed, 0x55, 0xbb, 0x6e, 0xaf, 0x3d, 0x70, 0x3a, 0x84, 0xa7, 0x25, 0x76,
	0x62, 0x59, 0xe3, 0x19, 0xf8, 0x74, 0x1f, 0xea, 0x41, 0xa4, 0x7c, 0x13, 0x43, 0x10, 0x84, 0xc8,
	0x72, 0x76, 0x09, 0xad, 0xe1, 0xc2, 0x08, 0xc5, 0x2d, 0x2e, 0x17, 0xcf, 0xb9, 0x3d, 0x48, 0x61,
	0x0f, 0x5b, 0xdf, 0xcc, 0xc6, 0xfd, 0xda, 0x3c, 0xc9, 0xd8, 0x2b, 0x81, 0x76, 0x6e, 0x80, 0x5e,
	0xe2, 0x04, 0xa1, 0xa3, 0x99, 0xc9, 0x26, 0x60, 0x56, 0xa6, 0x10, 0x0a, 0x6c, 0x1b, 0x2e, 0xca,
	0x99, 0xa6, 0xf4, 0x0c, 0x00, 0xc3, 0x8d, 0x00, 0xb1, 0x3e, 0xcd, 0xf3, 0x4e, 0x7f, 0x63, 0x4d,
	0xe6, 0x04, 0x6f, 0x98, 0x34, 0x64, 0xc7, 0xd0, 0x1c, 0xbe, 0x48, 0x93, 0xdb, 0x25, 0x61, 0x26,
	0x05, 0xe6, 0x2b, 0xbb, 0x73, 0xf6, 0xac, 0x84, 0x38, 0x47, 0xe6, 0x14, 0xc8, 0xd8, 0x1b, 0x01,
	0x3a, 0x5e, 0x06, 0xbe, 0x11, 0x5b, 0x0e, 0xfb, 0xc1, 0xdd, 0xa3, 0xc8, 0x99, 0xef, 0x14, 0xcd,
	0x2f, 0x58, 0xeb, 0xee, 0x58, 0x9b, 0x36, 0xc3, 0x55, 0x76, 0x16, 0xd8, 0xbc, 0xb1, 0x39, 0x8a,
	0x12, 0x3b, 0xbb, 0xbd, 0x8a, 0x9c, 0x28, 0xa9, 0xe5, 0x56, 0x94, 0x34, 0x64, 0x0f, 0xf0, 0xff,
	0x13, 0x6a, 0xc9, 0xd2, 0x45, 0xd1, 0x9d, 0x9f, 0x45, 0x3f, 0x82, 0x7f, 0xb7, 0x91, 0x50, 0xeb,
	0x32, 0x25, 0xd8, 0x3d, 0xd0, 0xdd, 0x47, 0xbf, 0xc9, 0x70, 0x0a, 0x1d, 0x1c, 0x3f, 0x58, 0x8f,
	0xd1, 0xe2, 0x32, 0xf7, 0x87, 0x09, 0xef, 0xf6, 0x6d, 0x42, 0xf2, 0xd5, 0xd9, 0x7f, 0x7b, 0x02,
	0xd3, 0x2a, 0xfe, 0x1c, 0x2e, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41, 0xa2, 0x93, 0x4f, 0x2b,
	0x04, 0x00, 0x00,
}
