// Code generated by protoc-gen-go.
// source: center.proto
// DO NOT EDIT!

/*
Package center is a generated protocol buffer package.

It is generated from these files:
	center.proto

It has these top-level messages:
	ConnInfo
	AddConnInfoReq
	AddConnInfoResp
	DelConnInfoReq
	DelConnInfoResp
	DelConnInfoByGateidReq
	DelConnInfoByGateidResp
	GetAllConnInfoReq
	GetAllConnInfoResp
	NewConnInfoNotify
	DelConnInfoNotify
	DelConnInfoByGateidNotify
*/
package center

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ConnInfo struct {
	Userid uint32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Gateid uint32 `protobuf:"varint,2,opt,name=gateid" json:"gateid,omitempty"`
	Connid uint32 `protobuf:"varint,3,opt,name=connid" json:"connid,omitempty"`
}

func (m *ConnInfo) Reset()                    { *m = ConnInfo{} }
func (m *ConnInfo) String() string            { return proto.CompactTextString(m) }
func (*ConnInfo) ProtoMessage()               {}
func (*ConnInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 添加连接信息
type AddConnInfoReq struct {
	Info *ConnInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *AddConnInfoReq) Reset()                    { *m = AddConnInfoReq{} }
func (m *AddConnInfoReq) String() string            { return proto.CompactTextString(m) }
func (*AddConnInfoReq) ProtoMessage()               {}
func (*AddConnInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddConnInfoReq) GetInfo() *ConnInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type AddConnInfoResp struct {
}

func (m *AddConnInfoResp) Reset()                    { *m = AddConnInfoResp{} }
func (m *AddConnInfoResp) String() string            { return proto.CompactTextString(m) }
func (*AddConnInfoResp) ProtoMessage()               {}
func (*AddConnInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 删除连接信息
type DelConnInfoReq struct {
	Gateid uint32 `protobuf:"varint,1,opt,name=gateid" json:"gateid,omitempty"`
	Connid uint32 `protobuf:"varint,2,opt,name=connid" json:"connid,omitempty"`
}

func (m *DelConnInfoReq) Reset()                    { *m = DelConnInfoReq{} }
func (m *DelConnInfoReq) String() string            { return proto.CompactTextString(m) }
func (*DelConnInfoReq) ProtoMessage()               {}
func (*DelConnInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DelConnInfoResp struct {
}

func (m *DelConnInfoResp) Reset()                    { *m = DelConnInfoResp{} }
func (m *DelConnInfoResp) String() string            { return proto.CompactTextString(m) }
func (*DelConnInfoResp) ProtoMessage()               {}
func (*DelConnInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 根据gateid删除连接信息
type DelConnInfoByGateidReq struct {
	Gateid uint32 `protobuf:"varint,1,opt,name=gateid" json:"gateid,omitempty"`
}

func (m *DelConnInfoByGateidReq) Reset()                    { *m = DelConnInfoByGateidReq{} }
func (m *DelConnInfoByGateidReq) String() string            { return proto.CompactTextString(m) }
func (*DelConnInfoByGateidReq) ProtoMessage()               {}
func (*DelConnInfoByGateidReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DelConnInfoByGateidResp struct {
}

func (m *DelConnInfoByGateidResp) Reset()                    { *m = DelConnInfoByGateidResp{} }
func (m *DelConnInfoByGateidResp) String() string            { return proto.CompactTextString(m) }
func (*DelConnInfoByGateidResp) ProtoMessage()               {}
func (*DelConnInfoByGateidResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 获取所有的连接信息
type GetAllConnInfoReq struct {
}

func (m *GetAllConnInfoReq) Reset()                    { *m = GetAllConnInfoReq{} }
func (m *GetAllConnInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GetAllConnInfoReq) ProtoMessage()               {}
func (*GetAllConnInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetAllConnInfoResp struct {
	Infos []*ConnInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
}

func (m *GetAllConnInfoResp) Reset()                    { *m = GetAllConnInfoResp{} }
func (m *GetAllConnInfoResp) String() string            { return proto.CompactTextString(m) }
func (*GetAllConnInfoResp) ProtoMessage()               {}
func (*GetAllConnInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetAllConnInfoResp) GetInfos() []*ConnInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

// 新增连接信息通知
type NewConnInfoNotify struct {
	Info *ConnInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *NewConnInfoNotify) Reset()                    { *m = NewConnInfoNotify{} }
func (m *NewConnInfoNotify) String() string            { return proto.CompactTextString(m) }
func (*NewConnInfoNotify) ProtoMessage()               {}
func (*NewConnInfoNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *NewConnInfoNotify) GetInfo() *ConnInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 删除连接信息通知
type DelConnInfoNotify struct {
	Info *ConnInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *DelConnInfoNotify) Reset()                    { *m = DelConnInfoNotify{} }
func (m *DelConnInfoNotify) String() string            { return proto.CompactTextString(m) }
func (*DelConnInfoNotify) ProtoMessage()               {}
func (*DelConnInfoNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DelConnInfoNotify) GetInfo() *ConnInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 根据gateid删除连接信息通知
type DelConnInfoByGateidNotify struct {
	Gateid uint32 `protobuf:"varint,1,opt,name=gateid" json:"gateid,omitempty"`
}

func (m *DelConnInfoByGateidNotify) Reset()                    { *m = DelConnInfoByGateidNotify{} }
func (m *DelConnInfoByGateidNotify) String() string            { return proto.CompactTextString(m) }
func (*DelConnInfoByGateidNotify) ProtoMessage()               {}
func (*DelConnInfoByGateidNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*ConnInfo)(nil), "center.ConnInfo")
	proto.RegisterType((*AddConnInfoReq)(nil), "center.AddConnInfoReq")
	proto.RegisterType((*AddConnInfoResp)(nil), "center.AddConnInfoResp")
	proto.RegisterType((*DelConnInfoReq)(nil), "center.DelConnInfoReq")
	proto.RegisterType((*DelConnInfoResp)(nil), "center.DelConnInfoResp")
	proto.RegisterType((*DelConnInfoByGateidReq)(nil), "center.DelConnInfoByGateidReq")
	proto.RegisterType((*DelConnInfoByGateidResp)(nil), "center.DelConnInfoByGateidResp")
	proto.RegisterType((*GetAllConnInfoReq)(nil), "center.GetAllConnInfoReq")
	proto.RegisterType((*GetAllConnInfoResp)(nil), "center.GetAllConnInfoResp")
	proto.RegisterType((*NewConnInfoNotify)(nil), "center.NewConnInfoNotify")
	proto.RegisterType((*DelConnInfoNotify)(nil), "center.DelConnInfoNotify")
	proto.RegisterType((*DelConnInfoByGateidNotify)(nil), "center.DelConnInfoByGateidNotify")
}

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4e, 0xcd, 0x2b,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x82, 0xb8, 0x38,
	0x9c, 0xf3, 0xf3, 0xf2, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0xc4, 0xb8, 0xd8, 0x4a, 0x8b, 0x53, 0x8b,
	0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0xa0, 0x3c, 0x90, 0x78, 0x7a, 0x62, 0x49,
	0x2a, 0x50, 0x9c, 0x09, 0x22, 0x0e, 0xe1, 0x81, 0xc4, 0x93, 0x81, 0x7a, 0x81, 0xe2, 0xcc, 0x10,
	0x71, 0x08, 0x4f, 0xc9, 0x8c, 0x8b, 0xcf, 0x31, 0x25, 0x05, 0x66, 0x6c, 0x50, 0x6a, 0xa1, 0x90,
	0x0a, 0x17, 0x4b, 0x26, 0x90, 0x09, 0x36, 0x97, 0xdb, 0x48, 0x40, 0x0f, 0xea, 0x14, 0xb8, 0x12,
	0xb0, 0xac, 0x92, 0x20, 0x17, 0x3f, 0x8a, 0xbe, 0xe2, 0x02, 0x25, 0x07, 0x2e, 0x3e, 0x97, 0xd4,
	0x1c, 0x64, 0xa3, 0x10, 0x8e, 0x61, 0xc4, 0xe1, 0x18, 0x26, 0x14, 0xc7, 0x00, 0x0d, 0x45, 0x31,
	0x01, 0x68, 0xa8, 0x01, 0x97, 0x18, 0x92, 0x90, 0x53, 0xa5, 0x3b, 0xd8, 0x04, 0x3c, 0x86, 0x2b,
	0x49, 0x72, 0x89, 0x63, 0xd5, 0x01, 0x34, 0x4c, 0x98, 0x4b, 0xd0, 0x3d, 0xb5, 0xc4, 0x31, 0x07,
	0xd9, 0x91, 0x4a, 0x36, 0x5c, 0x42, 0xe8, 0x82, 0xc5, 0x05, 0x42, 0x6a, 0x5c, 0xac, 0x20, 0x7f,
	0x16, 0x03, 0x0d, 0x67, 0xc6, 0x1a, 0x0c, 0x10, 0x69, 0x25, 0x4b, 0x2e, 0x41, 0xbf, 0xd4, 0x72,
	0x98, 0xa8, 0x5f, 0x7e, 0x49, 0x66, 0x5a, 0x25, 0x91, 0x41, 0x08, 0xd4, 0x8a, 0xe4, 0x50, 0x92,
	0xb4, 0x1a, 0x73, 0x49, 0x62, 0xf1, 0x23, 0xd4, 0x08, 0x1c, 0x01, 0x93, 0xc4, 0x06, 0x4e, 0x4d,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x06, 0xb1, 0xe7, 0x5d, 0x02, 0x00, 0x00,
}
